CREATE TABLE concept_view_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    viewed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT concept_view_history_concept_fk FOREIGN KEY (concept_id)
        REFERENCES concept (id) ON DELETE CASCADE
);

CREATE INDEX concept_view_history_viewed_at_concept_idx
    ON concept_view_history (viewed_at, concept_id);

CREATE INDEX concept_view_history_concept_viewed_idx
    ON concept_view_history (concept_id, viewed_at DESC, id DESC);

INSERT INTO concept_view_history (concept_id, viewed_at)
SELECT concept_id, first_viewed_at
FROM concept_progress
WHERE first_viewed_at IS NOT NULL
UNION
SELECT concept_id, last_viewed_at
FROM concept_progress
WHERE last_viewed_at IS NOT NULL;

CREATE INDEX attempt_dashboard_graded_at_idx
    ON attempt (graded_at DESC, id DESC)
    WHERE grading_status IN ('GRADED', 'SELF_CHECKED');
