CREATE TABLE learning_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    display_order SMALLINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT learning_area_slug_uk UNIQUE (slug),
    CONSTRAINT learning_area_display_order_ck CHECK (display_order > 0)
);

CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_area_id BIGINT NOT NULL,
    content_key VARCHAR(160) NOT NULL,
    slug VARCHAR(96) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT topic_area_fk FOREIGN KEY (learning_area_id)
        REFERENCES learning_area (id) ON DELETE RESTRICT,
    CONSTRAINT topic_content_key_uk UNIQUE (content_key),
    CONSTRAINT topic_area_slug_uk UNIQUE (learning_area_id, slug),
    CONSTRAINT topic_display_order_ck CHECK (display_order >= 0)
);

CREATE TABLE concept (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    content_key VARCHAR(160) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT,
    content_markdown TEXT NOT NULL,
    level SMALLINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT concept_topic_fk FOREIGN KEY (topic_id)
        REFERENCES topic (id) ON DELETE RESTRICT,
    CONSTRAINT concept_content_key_uk UNIQUE (content_key),
    CONSTRAINT concept_topic_slug_uk UNIQUE (topic_id, slug),
    CONSTRAINT concept_level_ck CHECK (level BETWEEN 1 AND 3),
    CONSTRAINT concept_status_ck CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT concept_display_order_ck CHECK (display_order >= 0)
);

CREATE TABLE concept_progress (
    concept_id BIGINT PRIMARY KEY,
    status VARCHAR(32) NOT NULL DEFAULT 'UNSEEN',
    bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
    first_viewed_at TIMESTAMPTZ,
    last_viewed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT concept_progress_concept_fk FOREIGN KEY (concept_id)
        REFERENCES concept (id) ON DELETE CASCADE,
    CONSTRAINT concept_progress_status_ck CHECK (status IN ('UNSEEN', 'LEARNING', 'COMPLETED', 'REVIEW_NEEDED'))
);

CREATE TABLE reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    title VARCHAR(300) NOT NULL,
    reference_type VARCHAR(32) NOT NULL,
    language_code VARCHAR(16),
    depth VARCHAR(32),
    recommendation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reference_url_uk UNIQUE (url),
    CONSTRAINT reference_type_ck CHECK (reference_type IN (
        'OFFICIAL', 'KOREAN_BLOG', 'COMPANY_TECH_BLOG', 'BOOK', 'PAPER', 'COURSE', 'OTHER'
    ))
);

CREATE TABLE concept_reference (
    concept_id BIGINT NOT NULL,
    reference_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    relation_note TEXT,
    CONSTRAINT concept_reference_pk PRIMARY KEY (concept_id, reference_id),
    CONSTRAINT concept_reference_concept_fk FOREIGN KEY (concept_id)
        REFERENCES concept (id) ON DELETE CASCADE,
    CONSTRAINT concept_reference_reference_fk FOREIGN KEY (reference_id)
        REFERENCES reference (id) ON DELETE RESTRICT,
    CONSTRAINT concept_reference_display_order_ck CHECK (display_order >= 0)
);

CREATE TABLE personal_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT personal_note_concept_uk UNIQUE (concept_id),
    CONSTRAINT personal_note_concept_fk FOREIGN KEY (concept_id)
        REFERENCES concept (id) ON DELETE CASCADE
);

CREATE INDEX learning_area_active_order_idx
    ON learning_area (active, display_order, id);

CREATE INDEX topic_area_active_order_idx
    ON topic (learning_area_id, active, display_order, id);

CREATE INDEX concept_topic_status_level_order_idx
    ON concept (topic_id, status, level, display_order, id);

CREATE INDEX concept_status_level_order_idx
    ON concept (status, level, display_order, id);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX concept_title_trgm_idx
    ON concept USING GIN (title gin_trgm_ops);

CREATE INDEX concept_summary_trgm_idx
    ON concept USING GIN (summary gin_trgm_ops);

CREATE INDEX concept_progress_status_viewed_idx
    ON concept_progress (status, last_viewed_at DESC, concept_id);

CREATE INDEX concept_progress_bookmarked_idx
    ON concept_progress (concept_id)
    WHERE bookmarked = TRUE;

CREATE INDEX concept_reference_reference_idx
    ON concept_reference (reference_id, concept_id);

INSERT INTO learning_area (slug, name, description, display_order)
VALUES
    ('computer-architecture', '컴퓨터 구조', '컴퓨터가 프로그램을 실행하는 구조와 동작 원리', 1),
    ('data-structures-algorithms', '자료구조 & 알고리즘', '문제를 구조화하고 효율적으로 해결하는 방법', 2),
    ('operating-systems', '운영체제', '프로세스, 메모리, 파일 시스템과 운영체제의 핵심 원리', 3),
    ('network-http', '네트워크 & HTTP', '네트워크 통신과 웹 프로토콜의 동작 방식', 4),
    ('database', '데이터베이스', '데이터 모델링, 저장, 조회와 트랜잭션의 기초', 5),
    ('java', 'Java', 'Java 언어와 JVM의 핵심 개념', 6),
    ('spring', 'Spring', 'Spring Framework와 애플리케이션 개발 핵심', 7),
    ('backend-engineering', 'Backend Engineering', '안정적이고 확장 가능한 백엔드 설계와 구현', 8),
    ('cache', '캐시', '캐시의 구조, 전략과 일관성 문제', 9),
    ('messaging-async', '메시징 & 비동기 처리', '메시지 브로커와 비동기 시스템의 설계 원리', 10),
    ('infrastructure-cloud', '인프라 & Cloud', '서비스를 운영하기 위한 인프라와 클라우드 기초', 11),
    ('performance-observability-operations', '성능 · 관측 · 운영', '성능 분석, 관측 가능성과 운영 자동화', 12),
    ('distributed-systems', '분산 시스템', '분산 환경에서의 일관성, 장애와 조정', 13),
    ('system-design', '시스템 디자인', '요구사항에서 확장 가능한 시스템으로 이어지는 설계', 14)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    display_order = EXCLUDED.display_order,
    active = TRUE,
    updated_at = CURRENT_TIMESTAMP;
