CREATE TABLE question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key VARCHAR(160) NOT NULL,
    prompt_markdown TEXT NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    difficulty VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    explanation_markdown TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_content_key_uk UNIQUE (content_key),
    CONSTRAINT question_type_ck CHECK (question_type IN (
        'MULTIPLE_CHOICE', 'SHORT_ANSWER', 'DESCRIPTIVE', 'SCENARIO'
    )),
    CONSTRAINT question_difficulty_ck CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT question_status_ck CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE question_choice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    choice_key VARCHAR(8) NOT NULL,
    content_markdown TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT question_choice_question_fk FOREIGN KEY (question_id)
        REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT question_choice_key_uk UNIQUE (question_id, choice_key),
    CONSTRAINT question_choice_order_uk UNIQUE (question_id, display_order),
    CONSTRAINT question_choice_order_ck CHECK (display_order >= 0)
);

CREATE TABLE question_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    answer_kind VARCHAR(32) NOT NULL,
    choice_id BIGINT,
    answer_text TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT question_answer_question_fk FOREIGN KEY (question_id)
        REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT question_answer_choice_fk FOREIGN KEY (choice_id)
        REFERENCES question_choice (id) ON DELETE CASCADE,
    CONSTRAINT question_answer_kind_ck CHECK (answer_kind IN (
        'CORRECT_CHOICE', 'ACCEPTED_TEXT', 'MODEL_ANSWER'
    )),
    CONSTRAINT question_answer_shape_ck CHECK (
        (answer_kind = 'CORRECT_CHOICE' AND choice_id IS NOT NULL AND answer_text IS NULL)
        OR (
            answer_kind IN ('ACCEPTED_TEXT', 'MODEL_ANSWER')
            AND choice_id IS NULL
            AND answer_text IS NOT NULL
            AND length(btrim(answer_text)) > 0
        )
    ),
    CONSTRAINT question_answer_order_ck CHECK (display_order >= 0)
);

CREATE TABLE question_concept (
    question_id BIGINT NOT NULL,
    concept_id BIGINT NOT NULL,
    CONSTRAINT question_concept_pk PRIMARY KEY (question_id, concept_id),
    CONSTRAINT question_concept_question_fk FOREIGN KEY (question_id)
        REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT question_concept_concept_fk FOREIGN KEY (concept_id)
        REFERENCES concept (id) ON DELETE RESTRICT
);

CREATE TABLE quiz_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMPTZ NOT NULL,
    submitted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    last_position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT quiz_session_status_ck CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'COMPLETED')),
    CONSTRAINT quiz_session_position_ck CHECK (last_position >= 0)
);

CREATE TABLE quiz_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT quiz_question_session_fk FOREIGN KEY (quiz_session_id)
        REFERENCES quiz_session (id) ON DELETE CASCADE,
    CONSTRAINT quiz_question_question_fk FOREIGN KEY (question_id)
        REFERENCES question (id) ON DELETE RESTRICT,
    CONSTRAINT quiz_question_session_question_uk UNIQUE (quiz_session_id, question_id),
    CONSTRAINT quiz_question_session_position_uk UNIQUE (quiz_session_id, position),
    CONSTRAINT quiz_question_position_ck CHECK (position >= 0)
);

CREATE TABLE attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_choice_id BIGINT,
    answer_text TEXT,
    review_needed BOOLEAN NOT NULL DEFAULT FALSE,
    grading_status VARCHAR(32) NOT NULL DEFAULT 'UNANSWERED',
    correct BOOLEAN,
    answered_at TIMESTAMPTZ,
    graded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attempt_session_fk FOREIGN KEY (quiz_session_id)
        REFERENCES quiz_session (id) ON DELETE CASCADE,
    CONSTRAINT attempt_question_fk FOREIGN KEY (question_id)
        REFERENCES question (id) ON DELETE RESTRICT,
    CONSTRAINT attempt_selected_choice_fk FOREIGN KEY (selected_choice_id)
        REFERENCES question_choice (id) ON DELETE RESTRICT,
    CONSTRAINT attempt_session_question_uk UNIQUE (quiz_session_id, question_id),
    CONSTRAINT attempt_grading_status_ck CHECK (grading_status IN (
        'UNANSWERED', 'GRADED', 'SELF_CHECK_REQUIRED', 'SELF_CHECKED'
    )),
    CONSTRAINT attempt_answer_shape_ck CHECK (selected_choice_id IS NULL OR answer_text IS NULL),
    CONSTRAINT attempt_grade_shape_ck CHECK (
        (grading_status IN ('UNANSWERED', 'SELF_CHECK_REQUIRED') AND correct IS NULL)
        OR (grading_status IN ('GRADED', 'SELF_CHECKED') AND correct IS NOT NULL)
    )
);

CREATE UNIQUE INDEX question_answer_correct_choice_uk
    ON question_answer (question_id)
    WHERE answer_kind = 'CORRECT_CHOICE';

CREATE UNIQUE INDEX question_answer_model_answer_uk
    ON question_answer (question_id)
    WHERE answer_kind = 'MODEL_ANSWER';

CREATE UNIQUE INDEX question_answer_accepted_text_uk
    ON question_answer (question_id, lower(btrim(answer_text)))
    WHERE answer_kind = 'ACCEPTED_TEXT';

CREATE INDEX question_published_selection_idx
    ON question (status, question_type, difficulty, updated_at DESC, id);

CREATE INDEX question_choice_question_order_idx
    ON question_choice (question_id, display_order, id);

CREATE INDEX question_answer_question_order_idx
    ON question_answer (question_id, display_order, id);

CREATE INDEX question_concept_concept_question_idx
    ON question_concept (concept_id, question_id);

CREATE INDEX quiz_session_status_started_idx
    ON quiz_session (status, started_at DESC, id DESC);

CREATE INDEX quiz_question_question_idx
    ON quiz_question (question_id, quiz_session_id);

CREATE INDEX attempt_question_answered_idx
    ON attempt (question_id, answered_at DESC, id DESC);
