ALTER TABLE quiz_session
    ADD COLUMN source VARCHAR(24) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE quiz_session
    ADD CONSTRAINT quiz_session_source_ck CHECK (source IN ('STANDARD', 'WRONG_RETRY', 'REVIEW'));

CREATE INDEX quiz_session_source_started_idx
    ON quiz_session (source, started_at DESC, id DESC);

CREATE TABLE wrong_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    wrong_count INTEGER NOT NULL,
    first_wrong_at TIMESTAMPTZ NOT NULL,
    last_wrong_at TIMESTAMPTZ NOT NULL,
    last_wrong_attempt_id BIGINT,
    cause_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wrong_note_question_uk UNIQUE (question_id),
    CONSTRAINT wrong_note_question_fk FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT wrong_note_last_attempt_fk FOREIGN KEY (last_wrong_attempt_id) REFERENCES attempt (id) ON DELETE SET NULL,
    CONSTRAINT wrong_note_status_ck CHECK (status IN ('ACTIVE', 'MASTERED')),
    CONSTRAINT wrong_note_count_ck CHECK (wrong_count >= 1)
);

CREATE INDEX wrong_note_status_recent_idx
    ON wrong_note (status, last_wrong_at DESC, id DESC);
CREATE INDEX wrong_note_count_idx
    ON wrong_note (wrong_count DESC, id DESC);

CREATE TABLE review_schedule (
    question_id BIGINT PRIMARY KEY,
    status VARCHAR(16) NOT NULL DEFAULT 'SCHEDULED',
    stage SMALLINT NOT NULL DEFAULT 1,
    due_at TIMESTAMPTZ,
    last_reviewed_at TIMESTAMPTZ,
    last_processed_attempt_id BIGINT,
    CONSTRAINT review_schedule_question_fk FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT review_schedule_last_attempt_fk FOREIGN KEY (last_processed_attempt_id) REFERENCES attempt (id) ON DELETE SET NULL,
    CONSTRAINT review_schedule_status_ck CHECK (status IN ('SCHEDULED', 'MASTERED')),
    CONSTRAINT review_schedule_stage_ck CHECK (stage BETWEEN 1 AND 4),
    CONSTRAINT review_schedule_due_ck CHECK (
        (status = 'SCHEDULED' AND due_at IS NOT NULL)
        OR (status = 'MASTERED' AND due_at IS NULL)
    )
);

CREATE INDEX review_schedule_status_due_idx
    ON review_schedule (status, due_at, question_id);
CREATE INDEX review_schedule_due_idx
    ON review_schedule (due_at, question_id);

CREATE TABLE review_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    quiz_session_id BIGINT NOT NULL,
    attempt_id BIGINT NOT NULL,
    result VARCHAR(16) NOT NULL,
    stage_before SMALLINT NOT NULL,
    stage_after SMALLINT,
    reviewed_at TIMESTAMPTZ NOT NULL,
    next_due_at TIMESTAMPTZ,
    CONSTRAINT review_history_question_fk FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE,
    CONSTRAINT review_history_session_fk FOREIGN KEY (quiz_session_id) REFERENCES quiz_session (id) ON DELETE CASCADE,
    CONSTRAINT review_history_attempt_fk FOREIGN KEY (attempt_id) REFERENCES attempt (id) ON DELETE CASCADE,
    CONSTRAINT review_history_attempt_uk UNIQUE (attempt_id),
    CONSTRAINT review_history_result_ck CHECK (result IN ('CORRECT', 'WRONG')),
    CONSTRAINT review_history_stage_ck CHECK (stage_before BETWEEN 1 AND 4 AND (stage_after IS NULL OR stage_after BETWEEN 1 AND 4))
);

CREATE INDEX review_history_question_recent_idx
    ON review_history (question_id, reviewed_at DESC, id DESC);
CREATE INDEX review_history_recent_idx
    ON review_history (reviewed_at DESC, id DESC);
