CREATE TABLE search_outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    change_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    last_error VARCHAR(2000),
    CONSTRAINT search_outbox_event_event_id_uk UNIQUE (event_id),
    CONSTRAINT search_outbox_event_change_type_ck CHECK (change_type IN (
        'TOPIC', 'CONCEPT', 'QUESTION', 'PERSONAL_NOTE', 'WRONG_NOTE', 'REFERENCE'
    )),
    CONSTRAINT search_outbox_event_source_id_ck CHECK (source_id > 0),
    CONSTRAINT search_outbox_event_attempt_count_ck CHECK (attempt_count >= 0)
);

CREATE UNIQUE INDEX search_outbox_event_pending_source_uk
    ON search_outbox_event (change_type, source_id)
    WHERE published_at IS NULL;

CREATE INDEX search_outbox_event_pending_due_idx
    ON search_outbox_event (next_attempt_at, id)
    WHERE published_at IS NULL;

CREATE INDEX search_outbox_event_created_idx
    ON search_outbox_event (id, created_at);
