CREATE TABLE wrong_answer_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wrong_note_id BIGINT NOT NULL,
    attempt_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    input_snapshot JSONB NOT NULL,
    result JSONB,
    provider VARCHAR(32) NOT NULL,
    model VARCHAR(160) NOT NULL,
    prompt_version VARCHAR(32) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    processing_token VARCHAR(64),
    processing_attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    requested_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wrong_answer_analysis_wrong_note_fk FOREIGN KEY (wrong_note_id)
        REFERENCES wrong_note (id) ON DELETE CASCADE,
    CONSTRAINT wrong_answer_analysis_attempt_fk FOREIGN KEY (attempt_id)
        REFERENCES attempt (id) ON DELETE CASCADE,
    CONSTRAINT wrong_answer_analysis_attempt_uk UNIQUE (attempt_id),
    CONSTRAINT wrong_answer_analysis_status_ck CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT wrong_answer_analysis_attempt_count_ck CHECK (processing_attempt_count >= 0)
);

CREATE INDEX wrong_answer_analysis_pending_idx
    ON wrong_answer_analysis (status, next_attempt_at, requested_at, id)
    WHERE status = 'PENDING';

CREATE INDEX wrong_answer_analysis_processing_idx
    ON wrong_answer_analysis (status, started_at, id)
    WHERE status = 'PROCESSING';
