import { Link, useNavigate, useSearch } from '@tanstack/react-router'
import { useMutation, useQuery } from '@tanstack/react-query'
import { ErrorState, PageSkeleton } from '../components/AsyncStates'
import { useToast } from '../components/toast/ToastProvider'
import { createReviewQuiz, getReviews, getReviewSummary } from '../lib/api'

export function ReviewPage() {
  const { showToast } = useToast()
  const search = useSearch({ from: '/review' })
  const navigate = useNavigate({ from: '/review' })
  const summary = useQuery({ queryKey: ['review-summary'], queryFn: getReviewSummary })
  const reviews = useQuery({ queryKey: ['reviews', search], queryFn: () => getReviews({ due: search.due, page: search.page, size: 20 }) })
  const create = useMutation({ mutationFn: () => createReviewQuiz(10), onSuccess: (quiz) => void navigate({ to: '/quiz/$quizId', params: { quizId: String(quiz.quizId) } }), onError: () => showToast('error', 'Review Quiz를 만들지 못했습니다.') })
  if (summary.isPending || reviews.isPending) return <PageSkeleton rows={5} />
  if (summary.isError || reviews.isError) return <ErrorState message="복습 일정을 불러오지 못했습니다." onRetry={() => { void summary.refetch(); void reviews.refetch() }} />
  const updateDue = (due: string) => void navigate({ search: (current) => ({ ...current, due, page: 0 }) })
  return <section className="page-section"><div className="page-heading"><div><p className="eyebrow">Spaced review</p><h1>Review</h1><p className="lead">오래된 일정부터 짧은 REVIEW Quiz로 회수하세요.</p></div><button className="primary-button" disabled={create.isPending || summary.data.dueNow === 0} onClick={() => create.mutate()}>{create.isPending ? 'Quiz 준비 중…' : 'Due 문제 10개 시작'}</button></div><div className="review-summary-grid"><div><span>Overdue</span><strong>{summary.data.overdue}</strong></div><div><span>Due now</span><strong>{summary.data.dueNow}</strong></div><div><span>Next 24h</span><strong>{summary.data.next24Hours}</strong></div><div><span>Next 7d</span><strong>{summary.data.next7Days}</strong></div><div><span>Mastered</span><strong>{summary.data.mastered}</strong></div></div><div className="filter-panel review-filters"><label>Window<select value={search.due} onChange={(event) => updateDue(event.target.value)}><option value="ALL">All</option><option value="OVERDUE">Overdue</option><option value="DUE">Due</option><option value="NEXT_24H">Next 24 hours</option><option value="NEXT_7D">Next 7 days</option></select></label></div>{reviews.data.items.length === 0 ? <div className="state-card"><strong>예정된 복습이 없습니다.</strong><span>오답 노트나 Quiz의 review needed를 통해 일정을 만들 수 있습니다.</span></div> : <div className="concept-list">{reviews.data.items.map((item) => <Link className="concept-list-item" key={item.questionId} to="/wrong-notes/$questionId" params={{ questionId: String(item.questionId) }}><div className="concept-list-main"><div className="chip-row"><span className="chip">Stage {item.stage}</span><span className="chip">{item.status}</span></div><h3>{item.promptMarkdown}</h3><p>{item.concepts.map((concept) => `${concept.areaName} · ${concept.title}`).join(', ')}</p></div><div className="wrong-note-metrics"><strong>{item.dueAt ? new Date(item.dueAt).toLocaleDateString() : 'Mastered'}</strong><span>Review item</span></div></Link>)}</div>}<div className="pagination"><button className="secondary-button" disabled={!reviews.data.page.hasPrevious} onClick={() => void navigate({ search: (current) => ({ ...current, page: Math.max(0, search.page - 1) }) })}>Previous</button><span>Page {search.page + 1}</span><button className="secondary-button" disabled={!reviews.data.page.hasNext} onClick={() => void navigate({ search: (current) => ({ ...current, page: search.page + 1 }) })}>Next</button></div></section>
}
