spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  application:
    name: csforge-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/csforge}
    username: ${DB_USERNAME:csforge}
    password: ${DB_PASSWORD:csforge}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-part-count: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  health:
    elasticsearch:
      enabled: ${ELASTICSEARCH_HEALTH_ENABLED:false}
